### ISSUE TITLE
Failing uninstall() and reinstall()

### ISSUE THREAD

**Issue by mdilena** [mottosso/apiundo#2]
#1 

There is an issue when uninstalling the module, where `__file__` in python 2.7 returns the .pyc and maya tries to unload that instead of apiundo.py, resulting in a non-existent plugin warning.
Also, when calling apiundo.py from a custom package hierarchy, the `__import__ `method will try to import the root package only, instead of the full import path (i.e. mypackage.subpackage.apiundo), resulting in an error when calling the install method from a wrong module.

**Comment by mottosso** [comment]
Thanks for reporting this, sorry for the delay; wasn't receiving notifications, but are now.

Any thoughts on what could be the cause?

**Comment by mottosso** [comment]
Just saw there was an [accompanying PR](https://github.com/mottosso/apiundo/pull/1) for this, thanks a bunch, merged!
